version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: zp-summit-db
    environment:
      POSTGRES_DB: zpsummit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zpsummit2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: